name: Build and Push Docker Image to ACR

on:
  workflow_dispatch:
  push:
    branches:
      - develop  # Puedes cambiar esto a la rama que prefieras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io

    - name: Build and push local Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest

    - name: Pull, tag, and push public Docker images to ACR
      run: |
        docker pull redis:7.0-alpine
        docker tag redis:7.0-alpine ${{ secrets.ACR_NAME }}.azurecr.io/redis:7.0-alpine
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/redis:7.0-alpine

        docker pull nginx:alpine
        docker tag nginx:alpine ${{ secrets.ACR_NAME }}.azurecr.io/nginx:alpine
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/nginx:alpine

        docker pull openzipkin/zipkin
        docker tag openzipkin/zipkin ${{ secrets.ACR_NAME }}.azurecr.io/zipkin:latest
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/zipkin:latest
