name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-app .

      - name: Run tests and build in Docker container
        run: |
          docker run --rm my-app npm install
          docker run --rm my-app npm run test

      - name: Run semantic-release in Docker container
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          docker run --rm -e GH_TOKEN="${{ secrets.GH_TOKEN }}" my-app npx semantic-release
