name: Semantic Release (Legacy)

on:
  push:
    branches: [ develop ]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: node:8.17-alpine
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Node
      run: |
        npm install -g npm@6.13.4
        node -v
        npm -v
        
    - name: Install Dependencies
      run: npm install
      
    - name: Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm install -g semantic-release@15
        npx semantic-release