name: Build and Release

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t my-app .
          docker push my-app:latest

      - name: Run Semantic Release
        run: |
          docker run --rm my-app semantic-release
