name: Draft Release Notes

on:
  push:
    branches:
      - master

jobs:
  draft_release_notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Release Drafter
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yml
        versioning-strategy: "auto"
